USE burp_backend;

CREATE TABLE IF NOT EXISTS cooks (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `age` INT NOT NULL,
     PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS users (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
     PRIMARY KEY (`id`)
);
